# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Appium iOS

on:
  push:
    branches:
      - main
      - cucumberRun3
      - exp

jobs:
  build:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode 13.2.1
        run: sudo xcode-select -s /Applications/Xcode_13.2.1.app
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/setup-node@v2
        with:
          node-version: '14.18.0'
      - run: |
          npm install -g appium
          appium -v
          appium &>/dev/null &
      - name: Run Appium IOS Tests
      - uses: actions/setup-node@v2
      - with:
          node-version: '14.18.0'
      - run: mvn clean test -Dcucumber.options="--tags @landIOS"

